server.port=${PORT:8081}
spring.main.banner-mode=off

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5434}/${PGDATABASE:certmgr}
spring.datasource.username=${PGUSER:certmgr}
spring.datasource.password=${PGPASSWORD:certmgr}
spring.datasource.hikari.maximum-pool-size=10
